### ISSUE TITLE
tabs in filename ... 

### ISSUE THREAD

**Issue by fbergmann** [derHahn/SBtab#20]
When I save the tsv as indicated in the last issue, and if i use a path that includes spaces, then SBtab will add a \t rather than a space in the filename. In the CSV export there will even be a comma in the filename. I don't think this should be the case. 

Some examples: 

```
!!SBtab	SBtabVersion='0.8'	Document='E:\Users\fbergmann\Documents\SBML	Models\Jana_WolfGlycolysis'	TableType='Compound'	TableName='Compound'	
```

or

```
!!SBtab,SBtabVersion='0.8',Document='\Users\fbergmann\Documents\SBML,Models\BorisEJB',TableType='Reaction',TableName='Reaction',,

```

**Comment by timolubitz** [comment]
This is fixed, thank you. It was due to an interface problem between SBtab and tablib.
